apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: transfer-service
  template:
    metadata:
      labels:
        app: transfer-service
    spec:
      containers:
        - name: transfer-service
          image: docker.io/nagabhushanamn/transfer-service:{{IMAGE_TAG}}
          