apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec: 
  selector:
    app: transfer-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort