pipeline{
    agent any
    stages{
         stage('Checkout') {
            steps {
                git url: 'https://github.com/nagcloudlab/dev-sec-ops.git', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                dir('transfer-service') {
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Test') {
            steps {
                dir('transfer-service') {
                    sh "mvn test"
                }
            }
        }
        stage('Package') {
            steps {
                dir('transfer-service') {
                    sh "mvn package -DskipTests"
                }
            }
        }
        stage('Deploy') {
            steps {
               withCredentials([file(credentialsId: 'nexus-credentials', variable: 'SETTINGS_XML')]) {
                    dir('transfer-service') {
                        sh 'mvn deploy -DskipTests -s $SETTINGS_XML'
                    }
                }
            }
        }


    }
}
    